# Generated by Django 5.2.17 on 2026-10-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_id_memberprofile'),
        ('tasks', '0004_expense_notes_expense_title_expense_user_and_more'),
    ]

    operations = [
    ]
